### ISSUE TITLE
[request] Add support for authenticating to Keycloak

### ISSUE THREAD

**Issue by joostdecock** [typesense/typesense-docsearch-scraper#39]
## Description

Sites that are behind a [Keycloak](https://www.keycloak.org/) setup can't be scraped because the scraper currently can't authenticate to it. 

## Steps to reproduce

Try scraping a site that's behind a Keycloak setup. 

## Expected Behavior

A [competing scraper](https://github.com/meilisearch/docs-scraper/blob/f9f782259860d98d109151637f2e34b77c2fb8e6/README.md#keycloak-access-identity-and-access-management-) supports this and even includes instructions in the README on how to configure it.

It would be nice if we could have a similar functionality.

## Actual Behavior

The scraper will be redirected, and index the Keycloak site (if you configure it to) but doesn't know how to authenticate.

## Metadata

**Typesense Version**: 0.24.1

**OS**: Debian Linux

**Comment by jasonbosco** [comment]
@joostdecock This seems to be the PR that adds Keycloak support in meilisearch docs-scraper: https://github.com/meilisearch/docs-scraper/pull/73.

Both Typesense and Meilisearch doc-scrapers are based on Algolia's docsearch-scraper. So the same set of changes when made in this repo should work. 

Since I don't use Keycloack, would be great if you're able to do a PR that adds this support based on the above PR and test it with your setup.

**Comment by joostdecock** [comment]
@jasonbosco Sounds good. I'll give it a stab.
